---
services:
  app:
    container_name: 'watcher-app'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WATCHER_API_KEY=$INFURA_API_KEY
      - WATCHER_DB_PASSWORD=mysecretpassword
    volumes:
      - "./config.yaml:/app/config.yaml"
    depends_on:
      - db
    command: python /app/run.py

  db:
    container_name: 'watcher-db'
    image: postgres:13
    environment:
      - POSTGRES_DB=watcher
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
