---
services:
  app:
    container_name: 'watcher-app'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WATCHER_API_KEY=$INFURA_API_KEY
      - WATCHER_DB_PASSWORD=mysecretpassword
    volumes:
      - "./config.yaml:/app/config.yaml"
    depends_on:
      - db
    command: python /app/run.py

  db:
    container_name: 'watcher-db'
    image: clickhouse/clickhouse-server:latest
    environment:
      - CLICKHOUSE_DB=watcher
      - CLICKHOUSE_USER=watcher
      - CLICKHOUSE_PASSWORD=mysecretpassword
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - "8123:8123"
      - "9070:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  clickhouse_data:
